name: Recent Activity Workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4 # <--- ESTO ES LO QUE PERMITE QUE VEA EL README

      - name: Actualizar actividad
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TITLE: "⚡ Mi Actividad Reciente"
